FROM ubuntu:latest

RUN mkdir /opt/build
WORKDIR /opt/build

RUN apt update && \
    apt install -y curl && \
    apt install -y tar && \
    apt install -y xz-utils && \
    apt download libgmp10 && \
    curl -sSL https://get.haskellstack.org/ | sh

# https://gist.github.com/TimWSpence/9b89b0915bf5224128e4b96abfd4ce02
RUN mv libgmp*.deb libgmp.deb
RUN dpkg -i /opt/build/libgmp.deb

RUN addgroup --system nixbld && \
    adduser --home /home/nix --disabled-password --gecos "" --shell /bin/bash nix && \
    adduser nix nixbld && \
    mkdir -m 0755 /nix && chown nix /nix && \
    mkdir -p /etc/nix && echo 'sandbox = false' > /etc/nix/nix.conf

CMD /bin/bash -l
USER nix
ENV USER nix
WORKDIR /home/nix

COPY --chown=nix:nix . .

RUN touch .bash_profile && deploy/nix.sh 

ENV PATH="/home/nix/bin:${PATH}"

# RUN git clone https://github.com/ImageMagick/ImageMagick.git && \
#     cd ImageMagick && git checkout 7.0.10-3 && \
#     ./configure --prefix=/home/nix && make && make install

RUN . /home/nix/.nix-profile/etc/profile.d/nix.sh && \
      stack install --fast -j12 --test

ENTRYPOINT ["/home/nix/deploy/init.sh"]